[install]
# Explicitly set the linker to isolated
linker = "isolated"

[test]
preload = "./happydom.ts"
coverage = true
root = "./test/unit"
coveragePathIgnorePatterns = [
    "**/models/openapi-ts/**"
]